version: 2.1

orbs:
  python: circleci/python@1.4.0

executors:
  python_postgres:
    docker:
      - image: cimg/python:3.8
      - image: circleci/postgres:10

jobs:
  try_psycopg2:
    executor: python_postgres
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: --dev
      - run: ls -la
      - run:
          name: Test
          command: pipenv run python ./try.py

workflows:
  showcase:
    jobs:
      - try_psycopg2
