version: 2.1

orbs:
  python: circleci/python@1.4.0

executors:
  python_postgres:
    docker:
      - image: cimg/python:3.7
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres123

jobs:
  try_psycopg2:
    executor: python_postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@localhost/circle_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: --dev
          pre-install-steps:
            - run: rm .python-version
      - run:
          name: Test
          command: pipenv run test

workflows:
  showcase:
    jobs:
      - try_psycopg2
